### PR TITLE
Feat/realtime

### PR DESCRIPTION
**Pull request by Merkur39**

### CODE REVIEW

**Comment by taratatach** [comment]
How are the changes made in `src/components/Contexts/FormDataProvider.jsx` related to the addition of realtime subscription?

**Comment by Merkur39** [comment]
>How are the changes made in `src/components/Contexts/FormDataProvider.jsx` related to the addition of realtime subscription?

All changes of 'io.cozy.files' doctype are tracked, and as FormDataProvider creates one or more files, the realtime detects it

**Comment by Merkur39** [comment]
Ah yes, it's indeed related 😅

**Comment by taratatach** [comment]
OK but how? I'm trying to understand these changes as they seem unrelated from here and you did not give any explanation in the commit message :slightly_smiling_face:.

**Comment by Merkur39** [comment]
Yes because by reloading, the DialogStepper was reset and therefore was doing the switch here https://github.com/cozy/mespapiers/blob/master/src/components/HomeWrapper/HomeWrapper.jsx

**Comment by taratatach** [comment]
Thanks for the explanation :).

**Pull request merged**
