### PR TITLE
feat: Add cozy-intent package

### PR DESCRIPTION
**Pull request by Merkur39**
Added `cozy-intent` to fix the BC in version 59 of cozy-ui (https://github.com/cozy/cozy-ui/releases/tag/v59.0.0)

### CODE REVIEW

**Comment by Crash--** [comment]
Can you wrap your app inside the provider please? https://github.com/cozy/cozy-home/blob/91323aa0dd61363c396b4c6e69616e66faff9da7/src/targets/browser/index.jsx#L25

**Comment by Crash--** [comment]
It is not specified in the UI's changelog? If not maybe it should?

**Comment by Merkur39** [comment]
> Can you wrap your app inside the provider please? https://github.com/cozy/cozy-home/blob/91323aa0dd61363c396b4c6e69616e66faff9da7/src/targets/browser/index.jsx#L25

In my case, the only addition of the package solved the problem, is it still necessary to systematically add the Provider?
If so, then indeed I would modify the UI changelog accordingly

**Comment by Crash--** [comment]
This is not really mandatory in order to have your build process working, but it'll be mandatory to have a communication layer between your application and the flagship app. Especially for the cozy-bar or to be able to open... a scanner mode for instance ;).

**Comment by Merkur39** [comment]
Ok, i updated the UI changelog 👍

**Review by JF-Cozy — APPROVED** [review]

**Pull request merged**
